In [1]:
import numpy as np
A = np.array([[13, 1], [14, 1], [15, 1], [16, 1], [17, 1], [18, 1]])
print(A)

[[13  1]
 [14  1]
 [15  1]
 [16  1]
 [17  1]
 [18  1]]


In [2]:
b = np.array([16,24,45,57,75,102])
print(b)

[ 16  24  45  57  75 102]


In [9]:
transpose_A= A.T # transpose of A
TA_dot_A = np.dot(transpose_A, A) # multiply tranpose of A and A
inv_TA_dot_A =  np.linalg.inv(TA_dot_A) # inverse previous result
TA_dot_b = np.dot(transpose_A, b) # multiply tranpose of A and B
x_matrix  = np.dot(inv_TA_dot_A, TA_dot_b)
print(x_matrix)


SyntaxError: invalid syntax (3533682528.py, line 6)

In [4]:
A_x_dot = np.dot(A, x_matrix) # multiply A and x matrix
# print(A_x_dot)
diff_A_x_dot_And_b = A_x_dot - b # get matrix difference
norm_final_matrix = np.linalg.norm(diff_A_x_dot_And_b) # get norm of the previous matrix
print(norm_final_matrix)

10.83205120618128


In [5]:
x_solution = np.linalg.solve(TA_dot_A, TA_dot_b)
print(x_solution)

[  17.         -210.33333333]


In [6]:
norm_final2 = np.linalg.norm(np.dot(A,x_solution)-b) # calculate again norm using the matrix calculated in the previous cell
print(norm_final2)

10.832051206181271


In [8]:
solved_system = np.linalg.lstsq(A, b, rcond=None) # solve system Ax = b
print(solved_system)

(array([  17.        , -210.33333333]), array([117.33333333]), 2, array([38.27438209,  0.26772348]))


## Transpuesta

La transpuesta de una matriz(expresada usualmente como A^t) donde las columnas son equivalentes a las filas de 
la matriz original.<br>
En consecuencia cada valor de la columna original cuyas coordenadas estaban en las coordenadas ij pasa a estar en las 
coordenadas ji.<br>
Ejemplo, si tenemos la matriz:
$$
  \begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix}
$$
Su transpuesta es: 
$$
  \begin{bmatrix}
1 & 3 \\
2 & 4 \\
\end{bmatrix}
$$

## Producto punto

la operación punto entre dos matrices (expresada como A*B) es un tipo de multiplicación de matrices donde el resultado final
es una nueva matriz con i filas (número de filas de la segunda matriz) y j columnas (número de columnas de la primera matriz)
y donde el valor de cada valor en coordenadas ij es la suma del producto de los valores de la fila i en A y de la columna 
j en B. Para poder hacer la operación punto la primera matriz debe tener un número de filas equivalente a las columnas de 
la segunda matriz .
ejemplo dee multiplicación de matrices:
$$
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix}
\cdot
\begin{bmatrix}
5 \\
6 \\
\end{bmatrix}
$$

Basado en la explicación anteriormente dada el resultado de esta multiplicación sería:
$$
\begin{bmatrix}
1 \times 5 + 2 \times 6 \\
3 \times 5 + 4 \times 6 \\
\end{bmatrix}
= 
\begin{bmatrix}
17 \\
39 \\
\end{bmatrix}
$$

## Matriz invertida

La matriz invertida se construye de la siguiente forma, teniendo una matriz de n x n, realizar operaciones sobre esta hasta obtener la matriz identidad, realizar las mismas operaciones sobre una matriz identidad y el resultado final de esta segunda matriz es la invertida. Ejemplo:
$$
\begin{bmatrix}
1 & 2 & 1 \\
2 & 3 & 1 \\
1 & 1 & 2 \\
\end{bmatrix}
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
$$
empezamos a construir la matriz triangular superior en la primera columna:
$$
\begin{bmatrix}
1 & 2 & 1 \\
0 & -1 & -1 \\
0 & -1 & 1 \\
\end{bmatrix}
\begin{bmatrix}
1 & 0 & 0 \\
-2 & 1 & 0 \\
-1 & 0 & 1 \\
\end{bmatrix}
$$
seguimos construyendo la matriz triangular con la segunda columna:
$$
\begin{bmatrix}
1 & 2 & 1 \\
0 & -1 & -1 \\
0 & 0 & 2 \\
\end{bmatrix}
\begin{bmatrix}
1 & 0 & 0 \\
-2 & 1 & 0 \\
1 & -1 & 1 \\
\end{bmatrix}
$$
empezamos a construir la matriz identidad en la última file:
$$
\begin{bmatrix}
1 & 2 & 0 \\
0 & -1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
\frac{1}{2} & \frac{1}{2} & \frac{-1}{2} \\
\frac{-3}{2} & \frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & \frac{-1}{2} & \frac{1}{2} \\
\end{bmatrix}
$$
continuamos con la primera fila:
$$
\begin{bmatrix}
1 & 0 & 0 \\
0 & -1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
\frac{-5}{2} & \frac{3}{2} & \frac{1}{2} \\
\frac{-3}{2} & \frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & \frac{-1}{2} & \frac{1}{2} \\
\end{bmatrix}
$$
terminamos de hacer la matriz identidad en la segunda fila:
$$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
\frac{-5}{2} & \frac{3}{2} & \frac{1}{2} \\
\frac{3}{2} & \frac{-1}{2} & \frac{-1}{2} \\
\frac{1}{2} & \frac{-1}{2} & \frac{1}{2} \\
\end{bmatrix}
$$

## Suma (o diferencia) de matrices

teníendo dos matrices A y B dodne ambas tienen las mismas dimensiones ij, la suma o diferencia es el resultado de sumar (o restar) cada par de valores de A y B que comparten las mismas coordenadas. Ejemplo:

$$
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix}
+
\begin{bmatrix}
5 & 6 \\
7 & 8 \\
\end{bmatrix}
=
\begin{bmatrix}
5+1 & 6+2 \\
7+3 & 8+4 \\
\end{bmatrix}
=
\begin{bmatrix}
6 & 8 \\
10 & 12 \\
\end{bmatrix}
$$

## Norma de un vector o una matriz

La norma de un vector o una matriz es la raiz cuadrada de los cuadrados de los componentes de la matriz o vector. Ejemplo, teniendo la siguiente matriz:
$$
\begin{bmatrix}
5 & 1 \\
7 & 5 \\
\end{bmatrix}
$$
la norma de esta matriz es:
$$
\sqrt{5^2 + 1^2 + 5^2 + 7^2} = \sqrt{25 + 1 + 25 + 49} = \sqrt{100} = 10
$$

## Resolver sistema lineal de ecuaciones

En términos algebráicos se puede expresar que resolver un sistema lineal de ecuaciones e encontrar x de la función:

$$
Ax=b
$$

Donde A es una matriz, x es la columna de las incógnitas y b es la columna vector dee términos independientes. Existen muchos métodos para encontrar la solución, una forma es invirtiendo la matriz, mediante sustitución,y también mediante el método crammer. En este último método vamos sustituyendo una de las columnas de A por la del vector b, encontramos la determinante de esta nueva matriz y la dividimos por la determinante de la matriz A, y repetimos para cada columna y así econtramos todas las incógnitas. Ejemplo, teniendo el siguiente sistema de ecuaciones:

$$
2x + y = 7
\\
x + 3y = 6
$$
para x tenemos que:
$$
\det 
\begin{bmatrix}
7 & 1 \\
6 & 3 \\
\end{bmatrix}
\div
\det
\begin{bmatrix}
2 & 1 \\
1 & 3 \\
\end{bmatrix}
= 
\frac{7 \times 3 - 1 \times 6}{2 \times 3 - 1 \times 1} 
= 
\frac{15}{5}
=
3
$$
Y para y tenemos:
$$
\det 
\begin{bmatrix}
2 & 7 \\
1 & 6 \\
\end{bmatrix}
\div
\det
\begin{bmatrix}
2 & 1 \\
1 & 3 \\
\end{bmatrix}
= 
\frac{2 \times 6 - 7 \times 1}{2 \times 3 - 1 \times 1} 
= 
\frac{5}{5}
=
1
$$
por lo tanto:
$$
x=3, y=1
$$